### ISSUE TITLE
EXPutt RG

### ISSUE THREAD

**Issue by Gaulfer** [Duwaynef/MLM2PRO-BT-APP#1]
Hello, not sure this where I should ask but will the connector work with EXputt RG to send putting metrics to GSPro? Thank you!

**Comment by simpystance** [comment]
Same question here!

**Comment by Duwaynef** [comment]
You can send exputt data if you open my connector, go to settings and enable the api relay server, reboot my connector after that.

From there you can use the mlm2pro ocr connector for your exputt, and set the ocr connectors gspro port to 951

It should then talk back and forth with gspro through my connector.

Worth also disabling the putting option in my settings so the webcam putting don't auto load on the green.

The ocr connector will get the club information and know when to read putts

**Comment by Gaulfer** [comment]
Thank you so much!

I’ll try that but I’m stuck at web api token!… I tried using the one in Joe
Lagowski’s video but saw the trpl_bgy had hidden his so I’m not sure… I’d
like to do this right.

I asked on discord a couple of times but nobody DMed me so far.

In any case, thank you for your help!

Kind regards.

Eric ( Gaulfer)

**Comment by Duwaynef** [comment]
i beleive you found the key after correct?

**Comment by Gaulfer** [comment]
Hello Duwayne,

Yes thank you, I believe it’s the same I saw in JLag’s YT video 🤭

Right now I’m just struggling to pair my launch monitor with my laptop… I
see it in the Bluetooth settings but when I try to connect, I get a “ Try
connecting your device again” message and it won’t connect…

Pretty much tried everything I found on the web but to no avail 😒

I’ll look at it again tonight.

Thanks again! Please trust that I will be supporting you on Kofy as soon as
I can make it work!

Eric

**Comment by Duwaynef** [comment]
Thank you for the support.

for the pairing the device with windows. are you on the beta update by chance?

**Comment by Gaulfer** [comment]
No, I'm on the latest version. I will be trying different things tonight to
try and get it to connect but the R10 was easy to connect... ;) I think
because it had a "pairing mode" ? ; solid blue. Should the MLM be flashing
blue or solid blue when attempting to pair it with my laptop? It's solid
blue after I authenticate with Awesome Golf... Maybe there is a detail
I'm missing?

Thank you.

Eric

**Comment by Duwaynef** [comment]
i just released an update, try the 0.9.8.3 version please.

i for sure had it working with the OCR connector. tested putting through it tonight

**Comment by Duwaynef** [comment]
No worries. i am looking into a solution for pairing. and i have seen that some people have a older bluetooth version on their computer and needed to get a newer bluetooth dongle that supported bluetooth 5.3.

**Comment by Gaulfer** [comment]
Yep, it seems I'm on 5.2...

**Comment by Duwaynef** [comment]
best to use springbok connnector for exputt, easiest way imo.

**Comment by Gaulfer** [comment]
Thanks!
