### ISSUE TITLE
Steamlink

### ISSUE THREAD

**Issue by andrew7447** [Duwaynef/MLM2PRO-BT-APP#16]
Is there anyway to get this to connect to my garage pc, that's streaming gspro via steamlink to my gaming pc in my basement?

You are a GOD btw 

Thanks.

**Comment by Duwaynef** [comment]
if the garage pc is windows based absolutely.

just run the connector on the garage pc.

on the GSPro pc, you need to open the firewall ports for GSPro open API, 921 by default i believe.

then in the connector settings on the garage pc you set the IP of your GSPro pc in the GSPro IP settings.

then play away.
