### ISSUE TITLE
Connection Error  - Trigging Discovery

### ISSUE THREAD

**Issue by reamesln** [Duwaynef/MLM2PRO-BT-APP#3]
I am having some issues connecting my MLM2 Pro. I am connected through my PC Bluetooth, entered in the web api code, and authenticated 3rd parties through the Rapsodo app.  When I try to connect through the launch I get a "Triggering Discovery" message. I attempted to restart the reconnect the device, as well as toggled on and off the Bluetooth with not no luck. Any suggestions on how to get this connected?

[debug error - triggering Discovery.txt](https://github.com/Duwaynef/MLM2PRO-BT-APP/files/14737849/debug.error.-.triggering.Discovery.txt)

![Triggering Discovery Error image](https://github.com/Duwaynef/MLM2PRO-BT-APP/assets/103122610/4c0f200a-375c-473c-97e5-28654660653a)

**Comment by Duwaynef** [comment]
you may need to unpair the device from windows, and pair it again.

it seems the communciation with the device broke down after the connection. this can happen when sometimes the device thinks the computer wants a smaller data transmission than normal ( like 27 MTU instead of 517 ).

**Comment by reamesln** [comment]
Thanks for the response @Duwaynef. I was using the built in Bluetooth from a cheap motherboard that only had support for BT 4.2. I bought a Bluetooth usb adapter with 5.3 and everything worked perfect on the first try. Not sure if the BT version made a difference or just that it was running from a cheap motherboard but if anyone else runs into a "Triggering Discovery" issue, a usb adapter may be a solution. Thank you for building this fantastic connector!
