### ISSUE TITLE
Cameras not working

### ISSUE THREAD

**Issue by arcticdouble** [Duwaynef/MLM2PRO-BT-APP#6]
I had a successful session on Saturday, it all performed perfectly.

I went to fire up today, launching the Rapsodo app to authenticate Awesome golf and then align, first.  

The cameras on the rapsodo unit don't connect to the app anymore.  I can't view the feed of either the impact camera or the swing camera for alignment.  Attempting to start a range session doesn't help.  The blue light won't turn green, indicating its ready for a shot.  I connected with this app to see if I could get it to read any shots and put them through to gspro, and it won't.  I have since restarted everything, reconnected, re-installed the firmware on the rapsodo, and the apps on the ipad and phone.  Nothing makes it work.  Awesome golf could get the blue light to turn green, but wouldn't detect any shots.  I didn't try E6.  The connector app doesn't receive any shot data from it, when I ARM it and led is green.  

I tried it all with an Ipad 10 and Galaxy S22.  Brand new Lenovo laptop, too.

DISARM does not change it from green back to blue anymore.

I'm at a loss on what to try next.  There is only one button on the thing, I've held it down for a minute if there is any "hard" reset that that does.  Else I have a bricked unit.  Any thoughts would be helpful.

**Comment by wonder99** [comment]
You did a good job debugging so far, but I didn't hear that you tried other wifi options. As far as I know, it's the wifi that's used to send the video streams, Bluetooth for the shot data.
Also, can you determine the signal strength of the wifi and Bluetooth?

**Comment by arcticdouble** [comment]
I did try it both direct and networked.  I’ve never had any connection issues. Had the unit since September. Signal strength varies fro -87 to -72 on the connector. Equates to 3 bars on the rhapsody app. Computer is 8 feet from the unit. iPad and phone are a couple feet from it.

**Comment by arcticdouble** [comment]
I know less how to measure the WiFi, but the three bars on the little WiFi symbol are there whether it’s a direct or network connection. My unit is probably 20 feet from the router. Again, never had the connection issues that others have had. Looking at a gc3 now

**Comment by Duwaynef** [comment]
I beleive we talked on discord is that correct?

**Comment by arcticdouble** [comment]
Yes, we did. I'll close the issue.

**Comment by wonder99** [comment]
Were you able to resolved your connection issue?

**Comment by arcticdouble** [comment]
No, haven't heard from Rapsodo, yet. I bet it'll be a week or two until I do. I've done everything possible, twice.

**Comment by arcticdouble** [comment]
Thank you
