### ISSUE TITLE
App token expired

### ISSUE THREAD

**Issue by tonzapower** [Duwaynef/MLM2PRO-BT-APP#8]
Howdy,
Let me start with a thank you - this is great.
My issue is having to reauthenticate with Awesome Golf every time I open it. I get the message app token expired - please authenticate in MLM software.
Could I have missed a step somewhere?

**Comment by wonder99** [comment]
The awesome golf authentication must be done every 24-30 hours. Unfortunately, there's nothing we can do about that. So it's a once per day annoyance.

**Comment by tonzapower** [comment]
Ok, thanks for letting me know. Just didn't want to find out there was an easier way later on :)
